version: '3.7'

networks:
  local:

services:
  db:
    image: "mongo:latest"
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - local
  web:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - local
